language: java
jdk:
  - openjdk8
os:
  - linux
cache:
  directories:
  - $HOME/.gradle
env:
  - NODE_VERSION=10.7
install:
  - nvm install $NODE_VERSION
  - npm install
script:
  - nvm use $NODE_VERSION
  - ./gradlew vscodeExtension --refresh-dependencies
after_success:
  - ./.travis-publishOnRelease.sh